version: "3.8"

services:
  traffic-sign-app:
    build: .
    container_name: traffic-sign-app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
